dist: trusty
language: php
php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - hhvm
matrix:
    allow_failures:
        - php: 5.6
        - php: hhvm
before_script:
    - composer install --no-interaction
script:
    - composer test
    - php vendor/bin/phpunit --coverage-clover build/coverage/xml
after_script:
    - php vendor/bin/codacycoverage clover build/coverage/xml
