dist: trusty
language: php
php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - hhvm
matrix:
    allow_failures:
        - php: 5.6
        - php: hhvm
before_script:
    - composer install --no-interaction
script:
    - composer test
after_script:
    - vendor/bin/codacycoverage clover temp/coverage/xml/codacy.xml
